name: FEniCS Performance Test CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 0,3"

jobs:
  build:
    runs-on: ubuntu-latest
    container: fenicsproject/test-env:openmpi

    env:
      CC: clang-10
      CXX: clang++-10

      PETSC_ARCH: linux-gnu-${{ matrix.petsc_arch }}-64
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
    
    strategy:
      matrix:
        petsc_arch: [real, complex]

    steps:
      - uses: actions/checkout@v2

      - name: Get Basix and install
        uses: actions/checkout@v2
        with:
          path: ./basix
          repository: FEniCS/basix
          ref: main

      - name: Install FEniCS Python components
        run: |
          apt-get -qq update
          apt-get -y install libboost-program-options-dev
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build-dir -S ./basix
          cmake --build build-dir
          cmake --install build-dir
          pip3 install ./basix/python
          pip3 install git+https://github.com/FEniCS/ufl.git
          pip3 install git+https://github.com/FEniCS/ffcx
      - name: Build dolfinx cpp
        run: |
          git clone -b main --single-branch https://github.com/FEniCS/dolfinx.git
          cd $(mktemp -d)
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE='-O2 -Wall -Wextra -pedantic -Werror'  $OLDPWD/dolfinx/cpp
          ninja install
      - name: Build performance test
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release  ../src
          ninja
      - name: Run Poisson test (GAMG, serial)
        run: |
          cd build/
          ./dolfinx-scaling-test \
          --problem_type poisson \
          --scaling_type weak \
          --ndofs 50000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg 
      - name: Run Poisson test (GAMG, weak)
        run: |
          cd build/
          mpirun -np 2 ./dolfinx-scaling-test \
          --problem_type poisson \
          --scaling_type weak \
          --ndofs 50000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg 
      - name: Run Poisson test (GAMG, weak, unstructured mesh)
        run: |
          cd build/
          mpirun -np 2 ./dolfinx-scaling-test \
          --problem_type poisson \
          --mesh_type unstructured \
          --scaling_type weak \
          --ndofs 50000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg
      - name: Run Poisson test (GAMG, strong)
        run: |
          cd build/
          mpirun -np 2 ./dolfinx-scaling-test \
          --problem_type poisson \
          --scaling_type strong \
          --ndofs 1000000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg
      - name: Run elasticity test (GAMG, serial)
        run: |
          cd build/
          ./dolfinx-scaling-test \
          --problem_type elasticity \
          --scaling_type weak \
          --ndofs 100000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg \
          -pc_gamg_coarse_eq_limit 1000 \
          -mg_levels_ksp_type chebyshev \
          -mg_levels_pc_type jacobi \
          -mg_levels_esteig_ksp_type cg \
          -matptap_via scalable
      - name: Run elasticity test (GAMG, weak)
        run: |
          cd build/
          mpirun -np 2 ./dolfinx-scaling-test \
          --problem_type elasticity \
          --scaling_type weak \
          --ndofs 100000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg \
          -pc_gamg_coarse_eq_limit 1000 \
          -mg_levels_ksp_type chebyshev \
          -mg_levels_pc_type jacobi \
          -mg_levels_esteig_ksp_type cg \
          -matptap_via scalable
      - name: Run elasticity test (GAMG, strong)
        run: |
          cd build/
          mpirun -np 2 ./dolfinx-scaling-test \
          --problem_type elasticity \
          --scaling_type strong \
          --ndofs 500000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg \
          -pc_gamg_coarse_eq_limit 1000 \
          -mg_levels_ksp_type chebyshev \
          -mg_levels_pc_type jacobi \
          -mg_levels_esteig_ksp_type cg \
          -matptap_via scalable
