name: FEniCS Performance Test CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 0,3"

jobs:
  build:
    runs-on: ubuntu-latest
    container: fenicsproject/performance-tests:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install FEniCS Python components
        run: |
          sudo apt-get update
          sudo apt-get install clang
          wget https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py
          pip3 install git+https://github.com/FEniCS/fiat.git --upgrade
          pip3 install git+https://github.com/FEniCS/ufl.git --upgrade
          pip3 install git+https://github.com/FEniCS/ffcx --upgrade
          rm -rf /usr/local/include/dolfin /usr/local/include/dolfin.h
      - name: Build dolfinx cpp
        env:
          PETSC_DIR: /usr/local/petsc-64
          CC: clang
          CXX: clang++
        run: |
          git clone --depth=1 --branch master https://github.com/FEniCS/dolfinx.git
          cd $(mktemp -d)
          cmake -G Ninja -j3 -DCMAKE_BUILD_TYPE=Release $OLDPWD/dolfinx/cpp
          ninja  install
      - name: Build performance test
        env:
          PETSC_DIR: /usr/local/petsc-64
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release  ../src
          ninja
      - name: Run Poisson test (BoomerAMG, weak)
        run: |
          cd build/
          mpirun -np 3 ./dolfinx-scaling-test \
          --problem_type poisson \
          --scaling_type weak \
          --ndofs 50000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type hypre \
          -pc_hypre_type boomeramg \
          -pc_hypre_boomeramg_strong_threshold 0.5
      - name: Run Poisson test (BoomerAMG, weak, unstructured mesh)
        run: |
          cd build/
          mpirun -np 3 ./dolfinx-scaling-test \
          --problem_type poisson \
          --mesh_type unstructured \
          --scaling_type weak \
          --ndofs 50000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type hypre \
          -pc_hypre_type boomeramg \
          -pc_hypre_boomeramg_strong_threshold 0.5
      - name: Run Poisson test (BoomerAMG, strong)
        run: |
          cd build/
          mpirun -np 3 ./dolfinx-scaling-test \
          --problem_type poisson \
          --scaling_type strong \
          --ndofs 1000000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type hypre \
          -pc_hypre_type boomeramg \
          -pc_hypre_boomeramg_strong_threshold 0.5
      - name: Run elasticity test (GAMG, weak)
        run: |
          cd build/
          mpirun -np 3 ./dolfinx-scaling-test \
          --problem_type elasticity \
          --scaling_type weak \
          --ndofs 100000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg \
          -pc_gamg_coarse_eq_limit 1000 \
          -mg_levels_ksp_type chebyshev \
          -mg_levels_pc_type jacobi \
          -mg_levels_esteig_ksp_type cg \
          -matptap_via scalable
      - name: Run elasticity test (GAMG, strong)
        run: |
          cd build/
          mpirun -np 3 ./dolfinx-scaling-test \
          --problem_type elasticity \
          --scaling_type strong \
          --ndofs 500000 \
          -log_view \
          -ksp_view \
          -ksp_type cg \
          -ksp_rtol 1.0e-8 \
          -pc_type gamg \
          -pc_gamg_coarse_eq_limit 1000 \
          -mg_levels_ksp_type chebyshev \
          -mg_levels_pc_type jacobi \
          -mg_levels_esteig_ksp_type cg \
          -matptap_via scalable
